cache: yarn

notifications:
  email: false

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - yarn build
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
