language: node_js
cache: yarn

notifications:
  email: false

jobs:
  include:
    - stage: release
      script:
        - yarn --frozen-lockfile && yarn build
      deploy:
        - provider: script
          skip_cleanup: true
          script: npx semantic-release
          on:
            branch: master
        - provider: script
          skip_cleanup: true
          script: npx semantic-release
          on:
            branch: develop
        - provider: pages
          github-token: $GH_TOKEN
          skip-cleanup: true
          local-dir: dist
          keep-history: true
          on:
            branch: master
