language: node_js
cache: yarn

notifications:
  email: false

jobs:
  include:
    - stage: release
      script:
        - yarn --frozen-lockfile && yarn build && yarn build/demo
      deploy:
        - provider: script
          skip_cleanup: true
          script: npx semantic-release
        - provider: pages
          github-token: $GH_TOKEN
          skip-cleanup: true
          local-dir: dist
          keep-history: false
          on:
            branch: master
