cache: yarn

notifications:
  email: false

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - yarn && yarn build
      deploy:
        - provider: script
          skip_cleanup: true
          script: npx semantic-release
        - provider: script
          skip_cleanup: true
          script: yarn deploy/demo
