language: node_js

script: yarn && yarn test && yarn build

deploy:
  provider: script
  skip_cleanup: true
  script:
    - yarn run semantic-release-pre
    - yarn publish build/
    - yarn run semantic-release-post

cache: yarn

notifications:
  email: false
