language: node_js
cache: yarn

notifications:
  email: false

jobs:
  include:
    - stage: release
      script:
        - yarn --frozen-lockfile && yarn build
      deploy:
        - provider: script
          skip_cleanup: true
          script: npx semantic-release
        - provider: script
          skip_cleanup: true
          script: yarn deploy/demo
          on:
            branch: master
