language: node_js

script: yarn && yarn test && yarn build-package

deploy:
  provider: script
  skip_cleanup: true
  script:
    - yarn run semantic-release-pre
    - cp package.json README.md ./dist
    - yarn publish dist/
    - yarn run semantic-release-post

cache: yarn

notifications:
  email: false
